### ISSUE TITLE
Pin 1 on hybrid footprints is incorrect

### ISSUE THREAD

**Issue by nooges** [egladman/keebs.pretty#2]
Based on the measurements from the Alps and MX datasheets, the size, location, and angle of the hybrid footprint for pin 1 incorrect. The position should be (-3.155, -3.27), the size should be (2.5, 4.4615), and the angle should be 1381 * 0.1 deg.

**Comment by egladman** [comment]
Finally got around to working on this, better late than never. I've used this footprint on handful of boards with success, but i'm thinking i got lucky with the tolerances after going back and reviewing switch spec sheets. I can see how the thru-hole for the Alps pin would need adjusting. I've gone ahead and tweaked the values (different from what you provided) to better accommodate the pins.

I'm going to do a little more testing before i merge into master.

Good catch.
