### ISSUE TITLE
Support for switches

### ISSUE THREAD

**Issue by sigboe** [egladman/keebs.pretty#4]
Does this library have support for Kailh Low Profile switches?
https://novelkeys.xyz/products/kailh-low-profile-switches

And support for breakout switches so you can make a frontplate from fiberglass cheap from a pcb fab?
https://imgur.com/a/mwTFj

**Comment by egladman** [comment]
Better late than never.... short answer: no

The current footprints don't support the low profile kalih switch (PG1350). I was able to find spec sheet [here](https://github.com/keyboardio/keyswitch_documentation/blob/master/datasheets/Kailh/CPG135001D02%20BROWN.pdf) to confirm my initial suspicions. The first pin is a ways off from the hole.
